import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/modules/navbar/Navbar";
import TopBar from "@/components/modules/topBar/TopBar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="fa" dir="rtl" className="h-full antialiased">
      <body className="min-h-screen flex flex-col bg-white">
        <div className="flex flex-1 flex-row-reverse">
          <div className="flex flex-col flex-1 min-h-0">
            <TopBar />
            <main className="flex-1 min-h-0 overflow-hidden">{children}</main>
          </div>
          <Navbar />
        </div>
      </body>
    </html>
  );
}
