import type { Metadata } from "next";
import "./globals.css";
import MainNavBar from "@/components/modules/mainPageNav/MainNavBar";
import Footer from "@/components/modules/Footer/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl" className="h-full antialiased">
      <body className="min-h-full flex flex-col bg-mainBgColor">
        <MainNavBar />

        {children}

        <Footer />
      </body>
    </html>
  );
}
